//! Files another tool owns.
//!
//! A lock file, a recorded seed list, a code generator's output: something else wrote the comments in these and will write them again.
//! Removing one is editing a tool's file, and it is the class most likely to be auto-fixed without being read, because nobody opens a generated file before committing it.
//!
//! This exists because of a wrong turn.
//! Closing the coverage gap by teaching OComment to read every format it met swept in nine `.proptest-regressions` files and reported sixty-eight findings in them — proptest's own header, in proptest's own format, above proptest's payload.
//! Coverage of a file you should not touch is worse than skipping it: a skip is visible in the summary, while a removal in a generated file is a diff somebody waves through.
//!
//! So these are skipped, under a reason of their own that `--deny-skipped` does not refuse — being passed over is what should happen to them — and `--include-generated` scans them anyway for the run that means it.

use anyhow::{Context, Result};
use serde::Deserialize;
use std::path::Path;

/// The catalogue, embedded so that it travels with the binary.
///
/// `spec/generated.toml` is the canonical copy;
/// `tools/check_embedded_specs.py` holds the two to each other.
const CATALOGUE: &str = include_str!("../assets/generated.toml");

/// The skip reason a generated file is counted under.
///
/// Its own reason rather than one of the existing ones, because it answers a different question: `unknown language` is a gap in what OComment can read,
/// and this is a decision about what it should read.
pub const REASON: &str = "generated file";

#[derive(Deserialize)]
struct Catalogue {
    #[serde(default)]
    filenames: Vec<String>,
    #[serde(default)]
    extensions: Vec<String>,
    #[serde(default)]
    headers: Vec<String>,
    #[serde(default)]
    header_lines: usize,
}

/// The catalogue, parsed once per run.
pub struct Generated {
    catalogue: Catalogue,
}

impl Generated {
    /// Read the embedded catalogue.
    pub fn load() -> Result<Self> {
        Ok(Self {
            catalogue: toml::from_str(CATALOGUE)
                .context("the embedded generated-file catalogue is not valid TOML")?,
        })
    }

    /// Whether this file is one another tool writes.
    ///
    /// The name is checked first because it costs nothing, then the first few lines.
    /// The line bound is what makes the header search usable: without it, a file that lists these markers claims itself, which this repository's own `spec/directives.toml` did by naming C#'s `<auto-generated`.
    /// A generated file declares itself at the top, where the reader it is warning will look.
    pub fn claims(&self, path: &Path, source: &[u8]) -> bool {
        if let Some(name) = path.file_name().and_then(|value| value.to_str())
            && self.catalogue.filenames.iter().any(|claim| claim == name)
        {
            return true;
        }
        if let Some(extension) = path.extension().and_then(|value| value.to_str())
            && self
                .catalogue
                .extensions
                .iter()
                .any(|claim| claim.eq_ignore_ascii_case(extension))
        {
            return true;
        }
        let head = String::from_utf8_lossy(source)
            .lines()
            .take(self.catalogue.header_lines)
            .collect::<Vec<_>>()
            .join("\n")
            .to_ascii_lowercase();
        self.catalogue
            .headers
            .iter()
            .any(|marker| head.contains(&marker.to_ascii_lowercase()))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_lock_file_is_claimed_by_its_name() {
        let generated = Generated::load().expect("the catalogue parses");
        assert!(generated.claims(Path::new("Cargo.lock"), b""));
        assert!(generated.claims(Path::new("a/b/package-lock.json"), b""));
        assert!(generated.claims(Path::new("x.proptest-regressions"), b""));
    }

    #[test]
    fn a_header_claims_a_file_whatever_it_is_called() {
        let generated = Generated::load().expect("the catalogue parses");
        assert!(generated.claims(Path::new("api.rs"), b"// @generated by tonic\n"));
        assert!(generated.claims(
            Path::new("api.go"),
            b"// Code generated by protoc. DO NOT EDIT.\n"
        ));
        assert!(generated.claims(
            Path::new("a.py"),
            b"# This file was generated; do not modify.\n"
        ));
    }

    /// The bound is the point: a file that lists these markers must not claim itself, and this repository has two that do -- the catalogue naming C#'s `<auto-generated`, and the catalogue of markers itself.
    #[test]
    fn a_marker_below_the_header_is_prose() {
        let generated = Generated::load().expect("the catalogue parses");
        let source = b"# A catalogue of markers.\n#\n# One line.\n# Another.\n# Filler.\n\
                       protected = [\"<auto-generated\", \"do not edit\"]\n";
        assert!(
            !generated.claims(Path::new("catalogue.toml"), source),
            "a file that lists the markers claimed itself"
        );
    }

    /// And the header itself is still found where a generated file puts it.
    #[test]
    fn a_header_in_the_first_lines_is_a_declaration() {
        let generated = Generated::load().expect("the catalogue parses");
        assert!(generated.claims(
            Path::new("anything.toml"),
            b"# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\n"
        ));
    }

    #[test]
    fn an_ordinary_source_is_not_claimed() {
        let generated = Generated::load().expect("the catalogue parses");
        assert!(!generated.claims(Path::new("main.rs"), b"// NOTE: written by a person\n"));
        assert!(!generated.claims(Path::new("Cargo.toml"), b"[package]\n"));
    }
}
