version = 1

protected = [
  "shebang", "encoding", "go:", "+build", "triple-slash-reference",
  "sourceMappingURL", "sourceURL", "#__PURE__", "@__PURE__",
  "lint-and-formatter", "type-checker", "optimizer-hint", "version-comment",
  "syntax=", "hadolint", ":schema", "taplo:", "---@diagnostic", "luacheck:",
  "selene:", "stylua:", "luacov:", "yaml-language-server:", "yamllint",
  "renovate:", "checkov:skip", "trivy:ignore", "nosec", "kics-scan", "@schema",
  "phpcs:", "@phpstan-ignore", "@psalm-suppress", "@codeCoverageIgnore",
  "frozen_string_literal:", "warn_indent:", "shareable_constant_value:",
  "rubocop:", "standard:", "typed:"
]

[policy.safe]
remove = ["line", "block", "doc-line", "doc-block", "license"]
keep = ["directive", "html-comment", "shebang", "encoding", "optimizer-hint", "version-comment"]

[policy.legal]
remove = ["line", "block", "doc-line", "doc-block"]
keep = ["license", "directive", "html-comment", "shebang", "encoding", "optimizer-hint", "version-comment"]

[policy.all]
remove = ["line", "block", "doc-line", "doc-block", "license", "directive", "html-comment", "optimizer-hint", "version-comment"]
keep_without_force_protected = ["shebang", "encoding"]
