#!/usr/bin/env python3
"""Regenerate the documentation pages that are derived rather than written.

Four pages under `docs/` restate something this repository already defines: the
CLI's own `--help` text, the shared language table, what each policy and layout
does to a fixed sample, and which markers survive a removal. A page like that is
stale the moment the thing it restates changes, and a stale page is worse than
no page at all, so it is generated here and `--check` fails the build when the
checked-in bytes and the regenerated bytes differ.

`--check` also compares `docs/ocomment.1` with the page `<binary> man` renders.
A Rust test pins the same file; both are kept, because that test proves the
shipped manual page still matches the parser, while this proves the
documentation site ships the page that was shipped.

Every example comes out of the built binary or out of `spec/`, never out of
prose, so nothing on the generated pages can claim behaviour the binary does not
have. Only the standard library is used, because this runs in a job that
installs nothing beyond the toolchain.
"""

from __future__ import annotations

import argparse
import difflib
import itertools
import json
import os
import pathlib
import re
import subprocess
import tempfile
import tomllib


ROOT = pathlib.Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
LANGUAGES = ROOT / "spec/languages.toml"
DIRECTIVES = ROOT / "spec/directives.toml"
MAN_PAGE = DOCS / "ocomment.1"
DEFAULT_BINARIES = (
    ROOT / "rust/target/debug/ocomment",
    ROOT / "rust/target/release/ocomment",
)

# INVARIANT: One sample for every name in the `protected` list of
# INVARIANT: `spec/directives.toml`, written the way a project really writes it
# INVARIANT: and holding exactly one comment. `protected_table` fails when the
# INVARIANT: spec names a marker that has no sample here, so a marker added to
# INVARIANT: the shared spec cannot reach a release undocumented, and it fails
# INVARIANT: again when the binary does not in fact keep one, so the table can
# INVARIANT: never promise a protection that is not there.
# NOTE: `tools/check_directives.py` proves the same names are protected, with
# NOTE: negative controls this page has no use for. The two lists are kept
# NOTE: apart on purpose: each is checked against the shared spec, and a docs
# NOTE: generator that imported a checker would fail for two different reasons
# NOTE: at once.
PROTECTED_SAMPLES: dict[str, tuple[str, str | None, bytes]] = {
    "shebang": ("shell", None, b"#!/bin/sh\n"),
    "encoding": ("python", None, b"# -*- coding: utf-8 -*-\n"),
    "go:": ("go", None, b"//go:build linux\n"),
    "+build": ("go", None, b"// +build linux\n"),
    "triple-slash-reference": (
        "typescript",
        None,
        b'/// <reference path="types.d.ts" />\n',
    ),
    "sourceMappingURL": ("javascript", None, b"//# sourceMappingURL=bundle.js.map\n"),
    "sourceURL": ("javascript", None, b"//# sourceURL=bundle.js\n"),
    "#__PURE__": ("javascript", None, b"const value = /*#__PURE__*/ factory();\n"),
    "@__PURE__": ("javascript", None, b"const value = /*@__PURE__*/ factory();\n"),
    "lint-and-formatter": (
        "javascript",
        None,
        b"// eslint-disable-next-line no-eval\n",
    ),
    "type-checker": ("python", None, b"value = 1  # type: ignore\n"),
    "optimizer-hint": ("sql", "oracle", b"select /*+ index(t) */ 1 from dual;\n"),
    "version-comment": ("sql", "mysql", b"/*!40101 SET NAMES utf8 */\n"),
    "syntax=": ("shell", None, b"# syntax=docker/dockerfile:1\n"),
    "hadolint": ("shell", None, b"# hadolint ignore=DL3018\n"),
}

BANNER = (
    "<!-- Generated by tools/gen_docs.py; edit that generator, not this page. -->"
)
REGENERATE = "python3 tools/gen_docs.py"


class Cli:
    """The built binary, run with an environment that cannot vary by machine.

    `HOME` and `XDG_CONFIG_HOME` are pointed at an empty directory so a user
    configuration file on the machine running this cannot reach the examples,
    and `NO_COLOR` is set so no run can escape into the page.
    """

    def __init__(self, binary: pathlib.Path, home: pathlib.Path) -> None:
        self.binary = binary
        self.environment = dict(os.environ)
        self.environment.update(
            {
                "NO_COLOR": "1",
                "TERM": "dumb",
                "HOME": str(home),
                "XDG_CONFIG_HOME": str(home / "config"),
            }
        )

    def run(
        self,
        arguments: list[str],
        *,
        source: bytes | None = None,
        cwd: pathlib.Path | None = None,
        expected: tuple[int, ...] = (0,),
    ) -> subprocess.CompletedProcess[bytes]:
        """Run the binary and refuse to document an exit code nobody expected."""
        completed = subprocess.run(
            [str(self.binary), *arguments],
            input=source,
            cwd=None if cwd is None else str(cwd),
            capture_output=True,
            env=self.environment,
        )
        if completed.returncode not in expected:
            raise SystemExit(
                f"`ocomment {' '.join(arguments)}` exited {completed.returncode},"
                f" expected one of {expected}\n"
                + completed.stderr.decode("utf-8", "replace")
            )
        return completed

    def text(self, arguments: list[str], **keywords) -> str:
        """The standard output of one run, decoded."""
        return self.run(arguments, **keywords).stdout.decode("utf-8")


def fence(language: str, body: str) -> str:
    """A fenced block that always ends in exactly one newline."""
    return f"```{language}\n{body.rstrip(chr(10))}\n```"


def anchor(heading: str) -> str:
    """The identifier mdBook gives a heading, so a link to it can be built."""
    return re.sub(r"[^a-z0-9]+", "-", heading.lower()).strip("-")


def cell(text: str) -> str:
    """One table cell: a pipe inside it would end the column early."""
    return text.replace("|", "\\|")


def count(number: int, singular: str, plural: str | None = None) -> str:
    """`1 file` and `2 files`, so the generated prose is never `1 files`."""
    return f"{number} {singular if number == 1 else (plural or singular + 's')}"


def commands_in(help_text: str) -> list[str]:
    """The subcommand names one `--help` page lists, in the order it lists them."""
    names: list[str] = []
    lines = help_text.splitlines()
    if "Commands:" not in lines:
        return names
    for line in lines[lines.index("Commands:") + 1 :]:
        if not line.strip():
            break
        match = re.match(r"^ {2}([a-z][a-z0-9-]*)(?:\s|$)", line)
        # NOTE: `help` prints the same page as `--help` and takes no options of
        # NOTE: its own, so documenting it would repeat every block on the page.
        if match is not None and match.group(1) != "help":
            names.append(match.group(1))
    return names


def command_paths(cli: Cli, path: tuple[str, ...] = ()) -> list[tuple[str, ...]]:
    """Every command the binary offers, parents before children.

    The list is discovered rather than written down, so a new subcommand is
    documented by the same change that adds it.
    """
    found = [path]
    for name in commands_in(cli.text([*path, "--help"])):
        found.extend(command_paths(cli, (*path, name)))
    return found


COMMANDS_INTRO = """\
# Commands

Each block below is the exact `--help` text of the binary this page was
generated from, so a flag documented here is a flag the tool has, and a flag
that is missing here does not exist.

`ocomment` with no command is `ocomment check`, and a command with no path is
the current directory. Findings, patches, listings, and every machine format go
to standard output; the run summary and every note go to standard error, so
`ocomment diff src > fix.patch` keeps the patch clean.

`check` exits `0` when nothing removable was found, `1` when removable comments
were reported or a diff was printed, and `2` for an invalid source,
configuration, plugin, or I/O failure.

The `Policy` and `Output` option groups are global. Every command that can act
on them accepts them, which is why the same two groups appear under most of the
blocks below. `ocomment man` renders the same material as a manual page."""


def commands_page(cli: Cli) -> str:
    """`docs/commands.md`: one `--help` block for every command, discovered."""
    paths = command_paths(cli)
    titles = [" ".join(("ocomment", *path)) for path in paths]
    lines = [BANNER, "", COMMANDS_INTRO, "", "## Contents", ""]
    lines.extend(f"- [`{title}`](#{anchor(title)})" for title in titles)
    for path, title in zip(paths, titles):
        help_text = cli.text([*path, "--help"])
        lines.extend(
            ["", f"## `{title}`", "", fence("console", f"$ {title} --help\n{help_text}")]
        )
    return "\n".join(lines) + "\n"


LANGUAGES_INTRO = """\
# Languages and dialects

`spec/languages.toml` is the canonical table. The `files:` pattern of the
published pre-commit hooks is generated from it, `tools/check_hooks.py` fails
when the two drift apart, and the table below is generated from the same file.
`ocomment languages` prints a shorter summary of it; this is the complete one.

A dialect changes the lexical rules rather than the file type: `--dialect
mysql` is still SQL, and only that dialect treats `/*!40101 ... */` as
something the server executes rather than as a comment.

A language is chosen from the file extension, and `--language` overrides that
for a run — which is what `ocomment strip` needs, because standard input has no
name. `--dialect` picks the dialect for the same run, and `[languages.<name>]
dialect = "..."` in `.ocomment.toml` picks one for everybody working in the
repository. An incompatible pair is an error rather than a silent fallback:

```console
$ ocomment strip --language rust --dialect mysql
ocomment: unsupported dialect `mysql` for rust; supported: standard
```
"""


def languages_page() -> str:
    """`docs/languages.md`: the shared language table, rendered."""
    with LANGUAGES.open("rb") as stream:
        table = tomllib.load(stream)
    entries = table["languages"]
    extensions = sorted({item for entry in entries for item in entry["extensions"]})
    dialects = sorted({item for entry in entries for item in entry["dialects"]})
    lines = [
        BANNER,
        "",
        LANGUAGES_INTRO,
        f"OComment has {count(len(entries), 'built-in language')} covering",
        f"{count(len(extensions), 'file extension')} and"
        f" {count(len(dialects), 'named dialect')}.",
        "",
        "| Language | Extensions | Dialects |",
        "| --- | --- | --- |",
    ]
    for entry in entries:
        suffixes = ", ".join(f"`.{item}`" for item in entry["extensions"])
        forms = ", ".join(f"`{item}`" for item in entry["dialects"])
        lines.append(f"| `{cell(entry['name'])}` | {cell(suffixes)} | {cell(forms)} |")
    lines.extend(
        [
            "",
            "## Anything else",
            "",
            "HTML is scanned recursively: the contents of a `<script>` element are",
            "scanned as JavaScript and the contents of a `<style>` element as CSS,",
            "each with the comment forms of that language rather than of HTML.",
            "",
            "A delimiter-based syntax that is not in the table above can be described",
            "declaratively as a profile in `.ocomment.toml`, which needs no code; see",
            "[Configuration](configuration.md). A syntax whose comments cannot be",
            "described by delimiters alone needs a scanner plugin instead; see",
            "[Plugins](plugins.md).",
        ]
    )
    return "\n".join(lines) + "\n"


POLICIES = ("safe", "legal", "all")
LAYOUTS = ("lines", "columns", "compact")

POLICY_SAMPLE = """\
// SPDX-License-Identifier: MIT OR Apache-2.0

// rustfmt::skip
/// Adds two numbers.
pub fn add(a: u32, b: u32) -> u32 {
    let total = a + /* widen */ b; // TODO: check for overflow
    /* Everything from here down is one block comment
       that runs across three lines, so each layout has
       something to show. */
    total
}
"""

POLICIES_INTRO = """\
# Policies and layouts

Two settings decide what a run does, and they are independent of each other. A
**policy** decides which comments may be removed at all. A **layout** decides
what is left behind where a removed comment used to be. Both are available as
`--policy` and `--layout` on the command line, as `mode` and `layout` under
`[policy]` in `.ocomment.toml`, and as `policy` and `layout` on an
`[[overrides]]` entry that matches a path.

Every before-and-after pair on this page was produced by running the sample
below through `ocomment strip`, so the outputs are the real bytes, trailing
spaces included."""


def policies_page(cli: Cli, workspace: pathlib.Path) -> str:
    """`docs/policies.md`: what each policy and layout does to a fixed sample.

    Every run is made from `workspace`, which holds no `.ocomment.toml`, so the
    outputs are what the named policy and layout do on their own rather than
    what this repository's own configuration would have made of the sample.
    """
    source = POLICY_SAMPLE.encode("utf-8")
    lines = [
        BANNER,
        "",
        POLICIES_INTRO,
        "",
        "## The sample",
        "",
        fence("rust", POLICY_SAMPLE),
        "",
        "It carries a licence header, a tool directive, a documentation comment,",
        "an inline block comment between two tokens, a trailing comment, and a",
        "block comment that spans several lines.",
        "",
        "## What each policy removes",
        "",
        "Each of these is `ocomment strip --language rust --policy <mode>` reading",
        "the sample on standard input.",
    ]
    for policy in POLICIES:
        output = cli.text(
            ["strip", "--language", "rust", "--policy", policy],
            source=source,
            cwd=workspace,
        )
        lines.extend(
            [
                "",
                f"### `{policy}`",
                "",
                fence("text", output),
            ]
        )
    lines.extend(
        [
            "",
            "`safe` and `legal` differ over the licence header alone, and `all`",
            "is the only one that takes the `// rustfmt::skip` directive out.",
            "`all` still refuses to touch a shebang or an encoding preamble until",
            "`--force-protected` is given as well; see",
            "[Why was this comment kept?](why-kept.md).",
            "",
            "## What each layout leaves behind",
            "",
            "Each of these is `ocomment strip --language rust --layout <layout>`",
            "reading the same sample, under the default `safe` policy.",
        ]
    )
    outputs = {}
    for layout in LAYOUTS:
        outputs[layout] = cli.text(
            ["strip", "--language", "rust", "--layout", layout],
            source=source,
            cwd=workspace,
        )
        lines.extend(["", f"### `{layout}`", "", fence("text", outputs[layout])])
    # INVARIANT: the paragraph below tells the reader that every layout keeps the
    # INVARIANT: line count of the file, which is the property that keeps a line
    # INVARIANT: number in a stack trace pointing at the same statement. A layout
    # INVARIANT: that stopped doing it has to fail here rather than ship a page
    # INVARIANT: that says it still does.
    expected_lines = POLICY_SAMPLE.count(chr(10))
    for layout, output in outputs.items():
        if output.count(chr(10)) != expected_lines:
            raise SystemExit(
                f"layout `{layout}` turned {expected_lines} lines into"
                f" {output.count(chr(10))}; docs/policies.md claims the line count"
                " is preserved"
            )
    same = [
        f"`{first}` and `{second}`"
        for first, second in itertools.combinations(LAYOUTS, 2)
        if outputs[first] == outputs[second]
    ]
    lines.append("")
    if same:
        lines.extend(
            [
                f"On this sample {' and '.join(same)} leave the same bytes.",
                "",
            ]
        )
    lines.extend(
        [
            "Every layout keeps the line count of the file: a comment that spanned",
            "three lines is replaced by something that still spans three lines, so",
            "a line number in a stack trace or a `git blame` still points at the",
            "same statement. `columns` additionally keeps every following column in",
            "place by padding with spaces, which is what a table of aligned",
            "initialisers or a column-sensitive language wants, at the cost of",
            "trailing whitespace that a formatter may then remove.",
            "",
            "## Where they are set",
            "",
            "```toml",
            "version = 1",
            "",
            "[policy]",
            'mode = "legal"',
            'layout = "lines"',
            "",
            "[[overrides]]",
            'paths = ["generated/**"]',
            'policy = "all"',
            'layout = "compact"',
            "```",
            "",
            "The flag wins over the file, and an `[[overrides]]` entry whose globs",
            "match the path wins over `[policy]`. `ocomment config explain` prints",
            "the resolved values and where each came from, and `ocomment --explain`",
            "names the rule and the setting behind any one comment.",
        ]
    )
    return "\n".join(lines) + "\n"


WHY_CONFIG = r"""version = 1

[policy]
mode = "safe"
keep_regex = ['^//\s*NOTE\b']

[[overrides]]
paths = ["gen/**"]
policy = "all"
keep_regex = ["(?i)generated"]
"""

WHY_FIXTURE = {
    "gen/api.rs": "/* generated by build.rs */\npub const VERSION: u32 = 1; // bump me\n",
    "src/app.js": "// eslint-disable-next-line no-console\nconsole.log(1); // TODO: drop\n",
    "src/lib.rs": "// NOTE: the retry budget is what the server documents.\nfn main() {}\n",
}

WHY_INTRO = """\
# Why was this comment kept?

A run that reports fewer comments than you expected has not lost them: it
decided to keep them, and it can say which rule decided. `--explain` lists every
comment a human `check` or `scan` met, the kept ones included, and puts the rule
and the setting behind that rule on the line under each one.

`--explain` annotates a report of comments, so it belongs to the two commands
that write one. Asking for it with `--format json`, or any other machine format,
or with a command that writes no report of comments, is a usage error rather
than a flag that quietly does nothing."""

WHY_WALKTHROUGH = """\
## Ask the binary

This project has a generated directory, a JavaScript file with a lint
directive, and a house rule that a `NOTE:` comment is deliberate:

```toml
%(config)s```

```text
%(tree)s```

`--explain` names the rule and the setting behind every comment it meets —
%(comments)s in this project:

```console
$ ocomment check --explain
%(transcript)s```

Read the second line of each pair as the answer. A `keep_regex` match kept the
first comment even though `[[overrides]]` puts the whole `gen/**` tree under the
`all` policy; a marker the scanner recognises kept the lint directive with no
configuration at all; and the setting in brackets is named where it was written,
so `[policy] in .ocomment.toml` and `[[overrides]] #0` point at the two places
that decided this run. A comment no setting decided is left with the flag that
would overrule the built-in rule instead."""


def scan_comments(
    cli: Cli, language: str, dialect: str | None, source: bytes, cwd: pathlib.Path
) -> list[dict]:
    """Every comment the binary reports for one sample, in source order."""
    arguments = ["scan", "--format", "json", "--language", language]
    if dialect is not None:
        arguments += ["--dialect", dialect]
    document = json.loads(cli.text(arguments + ["-"], source=source, cwd=cwd))
    return document["files"][0]["report"]["comments"]


def policy_matrix() -> list[str]:
    """The policy-by-kind table, straight out of `spec/directives.toml`."""
    with DIRECTIVES.open("rb") as stream:
        table = tomllib.load(stream)
    policies = {name: table["policy"][name] for name in POLICIES}
    kinds: list[str] = []
    for name in POLICIES:
        for key in ("remove", "keep", "keep_without_force_protected"):
            for kind in policies[name].get(key, []):
                if kind not in kinds:
                    kinds.append(kind)
    header = " | ".join(f"`{name}`" for name in POLICIES)
    lines = [
        f"| Comment kind | {header} |",
        "| --- | " + " | ".join(["---"] * len(POLICIES)) + " |",
    ]
    for kind in kinds:
        cells = []
        for name in POLICIES:
            policy = policies[name]
            if kind in policy.get("remove", []):
                cells.append("removed")
            elif kind in policy.get("keep", []):
                cells.append("kept")
            elif kind in policy.get("keep_without_force_protected", []):
                cells.append("kept unless `--force-protected`")
            else:
                # INVARIANT: a kind no policy mentions would render as an empty
                # INVARIANT: cell that reads like "nothing happens to it", which
                # INVARIANT: is a claim this table cannot make.
                raise SystemExit(
                    f"`{kind}` is in no list of policy `{name}` in"
                    f" {DIRECTIVES.relative_to(ROOT)}"
                )
        lines.append(f"| `{cell(kind)}` | " + " | ".join(cells) + " |")
    return lines


def protected_table(cli: Cli, cwd: pathlib.Path) -> list[str]:
    """One row per marker `spec/directives.toml` protects, scanned for real."""
    with DIRECTIVES.open("rb") as stream:
        names = tomllib.load(stream)["protected"]
    lines = [
        "| Marker | Language | Written as | Kind | Kept because |",
        "| --- | --- | --- | --- | --- |",
    ]
    for name in names:
        if name not in PROTECTED_SAMPLES:
            raise SystemExit(
                f"`{name}` is protected by {DIRECTIVES.relative_to(ROOT)} and has no"
                f" sample in {pathlib.Path(__file__).name}"
            )
        language, dialect, source = PROTECTED_SAMPLES[name]
        comments = scan_comments(cli, language, dialect, source, cwd)
        if len(comments) != 1:
            raise SystemExit(
                f"the sample for `{name}` holds {count(len(comments), 'comment')},"
                " so the row would describe the wrong one"
            )
        comment = comments[0]
        span = comment["span"]
        text = source[span["start"] : span["end"]].decode("utf-8")
        disposition = comment["disposition"]
        if disposition.get("action") != "keep":
            raise SystemExit(
                f"`{name}` is listed as protected but the binary reports"
                f" {disposition} for {text!r}"
            )
        lines.append(
            f"| `{cell(name)}` | `{cell(language if dialect is None else dialect)}` |"
            f" `{cell(text)}` | `{cell(comment['kind'])}` |"
            f" {cell(disposition['reason'])} |"
        )
    return lines


def why_kept_page(cli: Cli, workspace: pathlib.Path) -> str:
    """`docs/why-kept.md`: the rules that keep a comment, and how to see them."""
    fixture = workspace / "why-kept"
    for name, body in WHY_FIXTURE.items():
        path = fixture / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(body, encoding="utf-8", newline="\n")
    (fixture / ".ocomment.toml").write_text(WHY_CONFIG, encoding="utf-8", newline="\n")
    completed = cli.run(["check", "--explain"], cwd=fixture, expected=(1,))
    transcript = completed.stdout.decode("utf-8") + completed.stderr.decode("utf-8")
    tree = "".join(f"{name}\n" for name in [".ocomment.toml", *WHY_FIXTURE])
    # NOTE: a reported comment starts at the left margin and the rule under it is
    # NOTE: indented, so the unindented lines are the comments the run met.
    reported = sum(
        1
        for line in completed.stdout.decode("utf-8").splitlines()
        if line and not line.startswith(" ")
    )

    lines = [
        BANNER,
        "",
        WHY_INTRO,
        "",
        WHY_WALKTHROUGH
        % {
            "config": WHY_CONFIG,
            "tree": tree,
            "transcript": transcript,
            "comments": count(reported, "comment"),
        },
        "",
        "## What each policy removes",
        "",
        "`spec/directives.toml` is the shared table both implementations are",
        "checked against, and this is that table. `--policy` and `[policy] mode`",
        "choose a column, and the settings in the next sections move a single",
        "comment out of the column its kind lands in.",
        "",
    ]
    lines.extend(policy_matrix())
    lines.extend(
        [
            "",
            "## Markers that survive a removal",
            "",
            "Some comments are not commentary at all: a build tag, a lint control,",
            "or an optimiser hint changes what a compiler, a linter, or a database",
            "does with the file. Each row below is scanned by the binary that built",
            "this page, so the table cannot claim a protection that is not there.",
            "",
        ]
    )
    lines.extend(protected_table(cli, workspace))
    lines.extend(
        [
            "",
            "`--remove-kind directive` or `--policy all` removes a directive anyway.",
            "A shebang and an encoding preamble need `--force-protected` on top of",
            "`--policy all`, because removing one changes how the file is executed",
            "or decoded rather than how it reads.",
            "",
            "## Keeping more",
            "",
            "```toml",
            "version = 1",
            "",
            "[policy]",
            "keep_kind = [\"doc-line\", \"doc-block\"]",
            r"keep_regex = ['^(//|\(\*|/\*|#)\s*(NOTE|SAFETY|INVARIANT|PERF)\b']",
            "",
            "[[overrides]]",
            'paths = ["vendor/**"]',
            'policy = "legal"',
            "```",
            "",
            "`keep_kind` names whole kinds from the first column of the table above,",
            "so `keep_kind = [\"doc-line\", \"doc-block\"]` takes documentation out of",
            "reach of every policy. `keep_regex` matches the comment token itself,",
            "delimiters included, which is what lets `^//` anchor a rule to the start",
            "of the comment; this repository uses exactly that to require a tag on",
            "every explanatory comment it keeps. Both are lists, and `--explain`",
            "reports the index it matched, so `keep_regex #0` is the first entry.",
            "",
            "## Keeping less",
            "",
            "`--remove-kind` is the mirror of `keep_kind` and removes a kind the",
            "policy would have kept. `--policy all` removes every kind at once.",
            "`--force-protected` is needed on top of it for a shebang or an encoding",
            "preamble. `--force-invalid` applies the edits that are still provably",
            "safe in a file that failed to scan, and is the only one of these that",
            "is about a broken file rather than about a policy.",
            "",
            "## When the answer is still surprising",
            "",
            "`ocomment config explain` prints the resolved configuration and where",
            "each value came from, `ocomment doctor` reports the environment around",
            "it, and `ocomment scan --format json` gives the byte span and kind of",
            "every comment for a tool to read.",
        ]
    )
    return "\n".join(lines) + "\n"


def render(cli: Cli, workspace: pathlib.Path) -> dict[pathlib.Path, str]:
    """Every generated page, keyed by the file it belongs in."""
    return {
        DOCS / "commands.md": commands_page(cli),
        DOCS / "languages.md": languages_page(),
        DOCS / "policies.md": policies_page(cli, workspace),
        DOCS / "why-kept.md": why_kept_page(cli, workspace),
    }


def difference(path: pathlib.Path, expected: str, actual: bytes | None) -> str:
    """What to print about one page that is missing or out of date."""
    relative = path.relative_to(ROOT)
    if actual is None:
        return f"{relative} does not exist"
    diff = difflib.unified_diff(
        actual.decode("utf-8", "replace").splitlines(keepends=True),
        expected.splitlines(keepends=True),
        fromfile=f"{relative} (checked in)",
        tofile=f"{relative} (regenerated)",
        n=1,
    )
    body = "".join(itertools.islice(diff, 40))
    return f"{relative} is out of date\n{body.rstrip(chr(10))}"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--binary",
        type=pathlib.Path,
        help="the ocomment to generate from (default: the debug or release build)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of writing when a page is missing or out of date",
    )
    args = parser.parse_args()

    binary = args.binary
    if binary is None:
        binary = next((path for path in DEFAULT_BINARIES if path.is_file()), None)
        if binary is None:
            parser.error(
                "no ocomment binary was found; build one with"
                " `cargo build --manifest-path rust/Cargo.toml --locked -p ocomment`"
                " or name one with --binary"
            )
    binary = binary.resolve()
    if not binary.is_file():
        parser.error(f"CLI binary does not exist: {binary}")

    failures: list[str] = []
    with tempfile.TemporaryDirectory() as directory:
        workspace = pathlib.Path(directory)
        (workspace / "config").mkdir()
        cli = Cli(binary, workspace)

        rendered = cli.run(["man"]).stdout
        if not MAN_PAGE.is_file():
            failures.append(f"{MAN_PAGE.relative_to(ROOT)} does not exist")
        elif MAN_PAGE.read_bytes() != rendered:
            failures.append(
                f"{MAN_PAGE.relative_to(ROOT)} is not what `ocomment man` renders;"
                " regenerate it with `python3 tools/release_extras.py"
                " --binary rust/target/debug/ocomment` and copy"
                " release-extras/ocomment.1 to docs/"
            )

        pages = render(cli, workspace)
        written = 0
        stale = 0
        for path, expected in pages.items():
            wanted = expected.encode("utf-8")
            actual = path.read_bytes() if path.is_file() else None
            if actual == wanted:
                continue
            if args.check:
                failures.append(difference(path, expected, actual))
                stale += 1
            else:
                path.write_bytes(wanted)
                written += 1

    if failures:
        print("\n".join(failures))
        # NOTE: the manual page is checked here but written by another tool, so
        # NOTE: naming this one would send a reader to a command that cannot fix
        # NOTE: what they were just told about.
        if stale:
            print(f"Regenerate with: {REGENERATE}")
        return 1
    if args.check:
        print(
            f"{count(len(pages), 'generated documentation page')}"
            " and the manual page match the binary and spec/"
        )
    else:
        print(
            f"{count(written, 'generated documentation page')} rewritten;"
            f" {count(len(pages) - written, 'page')} already current"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
