#!/usr/bin/env python3
"""Regenerate the documentation pages that are derived rather than written.

Four pages under `docs/` restate something this repository already defines: the
CLI's own `--help` text, the shared language table, what each policy and layout
does to a fixed sample, and which markers survive a removal. A page like that is
stale the moment the thing it restates changes, and a stale page is worse than
no page at all, so it is generated here and `--check` fails the build when the
checked-in bytes and the regenerated bytes differ.

`--check` also compares `docs/ocomment.1` with the page `<binary> man` renders.
A Rust test pins the same file; both are kept, because that test proves the
shipped manual page still matches the parser, while this proves the
documentation site ships the page that was shipped.

Every example comes out of the built binary or out of `spec/`, never out of
prose, so nothing on the generated pages can claim behaviour the binary does not
have. Only the standard library is used, because this runs in a job that
installs nothing beyond the toolchain.
"""

from __future__ import annotations

import argparse
import difflib
import itertools
import json
import os
import pathlib
import re
import subprocess
import tempfile
import tomllib


ROOT = pathlib.Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
LANGUAGES = ROOT / "spec/languages.toml"
DIRECTIVES = ROOT / "spec/directives.toml"
MAN_PAGE = DOCS / "ocomment.1"
DEFAULT_BINARIES = (
    ROOT / "rust/target/debug/ocomment",
    ROOT / "rust/target/release/ocomment",
)

# INVARIANT: One sample for every name in the `protected` list of
# INVARIANT: `spec/directives.toml`, written the way a project really writes it
# INVARIANT: and holding exactly one comment. `protected_table` fails when the
# INVARIANT: spec names a marker that has no sample here, so a marker added to
# INVARIANT: the shared spec cannot reach a release undocumented, and it fails
# INVARIANT: again when the binary does not in fact keep one, so the table can
# INVARIANT: never promise a protection that is not there.
# NOTE: `tools/check_directives.py` proves the same names are protected, with
# NOTE: negative controls this page has no use for. The two lists are kept
# NOTE: apart on purpose: each is checked against the shared spec, and a docs
# NOTE: generator that imported a checker would fail for two different reasons
# NOTE: at once.
PROTECTED_SAMPLES: dict[str, tuple[str, str | None, bytes]] = {
    "shebang": ("shell", None, b"#!/bin/sh\n"),
    "encoding": ("python", None, b"# -*- coding: utf-8 -*-\n"),
    "go:": ("go", None, b"//go:build linux\n"),
    "+build": ("go", None, b"// +build linux\n"),
    "triple-slash-reference": (
        "typescript",
        None,
        b'/// <reference path="types.d.ts" />\n',
    ),
    "sourceMappingURL": ("javascript", None, b"//# sourceMappingURL=bundle.js.map\n"),
    "sourceURL": ("javascript", None, b"//# sourceURL=bundle.js\n"),
    "#__PURE__": ("javascript", None, b"const value = /*#__PURE__*/ factory();\n"),
    "@__PURE__": ("javascript", None, b"const value = /*@__PURE__*/ factory();\n"),
    "lint-and-formatter": (
        "javascript",
        None,
        b"// eslint-disable-next-line no-eval\n",
    ),
    "type-checker": ("python", None, b"value = 1  # type: ignore\n"),
    "optimizer-hint": ("sql", "oracle", b"select /*+ index(t) */ 1 from dual;\n"),
    "version-comment": ("sql", "mysql", b"/*!40101 SET NAMES utf8 */\n"),
    "syntax=": ("shell", None, b"# syntax=docker/dockerfile:1\n"),
    "hadolint": ("shell", None, b"# hadolint ignore=DL3018\n"),
    ":schema": ("toml", None, b"#:schema https://example.test/pyproject.json\n"),
    "taplo:": ("toml", None, b"# taplo: array_auto_expand = false\n"),
    "---@diagnostic": (
        "lua",
        None,
        b"---@diagnostic disable-next-line: undefined-global\n",
    ),
    "luacheck:": ("lua", None, b"-- luacheck: ignore 212\n"),
    "selene:": ("lua", None, b"-- selene: allow(unused_variable)\n"),
    "stylua:": ("lua", None, b"-- stylua: ignore\n"),
    "luacov:": ("lua", None, b"-- luacov: disable\n"),
    "yaml-language-server:": (
        "yaml",
        None,
        b"# yaml-language-server: $schema=https://example.test/schema.json\n",
    ),
    "yamllint": ("yaml", None, b"# yamllint disable-line rule:line-length\n"),
    "renovate:": ("yaml", None, b"# renovate: datasource=docker depName=alpine\n"),
    "checkov:skip": ("yaml", None, b"# checkov:skip=CKV_AWS_20:public by design\n"),
    "trivy:ignore": ("yaml", None, b"# trivy:ignore:AVD-AWS-0089\n"),
    "nosec": ("yaml", None, b"# nosec\n"),
    "kics-scan": ("yaml", None, b"# kics-scan ignore-line\n"),
    "@schema": ("yaml", None, b"# @schema type: string\n"),
    "phpcs:": ("php", None, b"<?php\n// phpcs:ignore Squiz.Commenting.FunctionComment\n"),
    "@phpstan-ignore": ("php", None, b"<?php\n// @phpstan-ignore-next-line\n"),
    "@psalm-suppress": (
        "php",
        None,
        b"<?php\n/** @psalm-suppress InvalidReturnType */\n",
    ),
    "@codeCoverageIgnore": ("php", None, b"<?php\n// @codeCoverageIgnoreStart\n"),
    "frozen_string_literal:": ("ruby", None, b"# frozen_string_literal: true\n"),
    "warn_indent:": ("ruby", None, b"# warn_indent: true\n"),
    "shareable_constant_value:": (
        "ruby",
        None,
        b"# shareable_constant_value: literal\n",
    ),
    "rubocop:": ("ruby", None, b"# rubocop:disable Style/Documentation\n"),
    "standard:": ("ruby", None, b"# standard:disable Style/StringLiterals\n"),
    "typed:": ("ruby", None, b"# typed: strict\n"),
    "zig fmt:": ("zig", None, b"// zig fmt: off\n"),
    "styler:": ("r", None, b"# styler: off\n"),
    "nocov": ("r", None, b"# nocov start\n"),
    "@dart": ("dart", None, b"// @dart = 2.12\n"),
    "dart format": ("dart", None, b"// dart format off\n"),
    "ignore:": ("dart", None, b"// ignore: unused_local_variable\n"),
    "ignore_for_file:": ("dart", None, b"// ignore_for_file: unused_import\n"),
    "swift-tools-version:": ("swift", None, b"// swift-tools-version:5.9\n"),
    "swiftlint:": ("swift", None, b"// swiftlint:disable force_cast\n"),
    "swiftformat:": ("swift", None, b"// swiftformat:disable redundantSelf\n"),
    "swift-format-ignore": ("swift", None, b"// swift-format-ignore\n"),
    "<auto-generated": ("csharp", None, b"// <auto-generated/>\n"),
    "ReSharper": ("csharp", None, b"// ReSharper disable once UnusedMember.Local\n"),
    "csharpier-ignore": ("csharp", None, b"// csharpier-ignore\n"),
    "//> using": ("scala", None, b'//> using scala "3.3.0"\n'),
}

BANNER = (
    "<!-- Generated by tools/gen_docs.py; edit that generator, not this page. -->"
)
REGENERATE = "python3 tools/gen_docs.py"


class Cli:
    """The built binary, run with an environment that cannot vary by machine.

    `HOME` and `XDG_CONFIG_HOME` are pointed at an empty directory so a user
    configuration file on the machine running this cannot reach the examples,
    and `NO_COLOR` is set so no run can escape into the page.
    """

    def __init__(self, binary: pathlib.Path, home: pathlib.Path) -> None:
        self.binary = binary
        self.environment = dict(os.environ)
        self.environment.update(
            {
                "NO_COLOR": "1",
                "TERM": "dumb",
                "HOME": str(home),
                "XDG_CONFIG_HOME": str(home / "config"),
            }
        )

    def run(
        self,
        arguments: list[str],
        *,
        source: bytes | None = None,
        cwd: pathlib.Path | None = None,
        expected: tuple[int, ...] = (0,),
    ) -> subprocess.CompletedProcess[bytes]:
        """Run the binary and refuse to document an exit code nobody expected."""
        completed = subprocess.run(
            [str(self.binary), *arguments],
            input=source,
            cwd=None if cwd is None else str(cwd),
            capture_output=True,
            env=self.environment,
        )
        if completed.returncode not in expected:
            raise SystemExit(
                f"`ocomment {' '.join(arguments)}` exited {completed.returncode},"
                f" expected one of {expected}\n"
                + completed.stderr.decode("utf-8", "replace")
            )
        return completed

    def text(self, arguments: list[str], **keywords) -> str:
        """The standard output of one run, decoded."""
        return self.run(arguments, **keywords).stdout.decode("utf-8")


def fence(language: str, body: str) -> str:
    """A fenced block that always ends in exactly one newline."""
    return f"```{language}\n{body.rstrip(chr(10))}\n```"


def anchor(heading: str) -> str:
    """The identifier mdBook gives a heading, so a link to it can be built."""
    return re.sub(r"[^a-z0-9]+", "-", heading.lower()).strip("-")


def cell(text: str) -> str:
    """One table cell: a pipe inside it would end the column early."""
    return text.replace("|", "\\|")


def count(number: int, singular: str, plural: str | None = None) -> str:
    """`1 file` and `2 files`, so the generated prose is never `1 files`."""
    return f"{number} {singular if number == 1 else (plural or singular + 's')}"


def commands_in(help_text: str) -> list[str]:
    """The subcommand names one `--help` page lists, in the order it lists them."""
    names: list[str] = []
    lines = help_text.splitlines()
    if "Commands:" not in lines:
        return names
    for line in lines[lines.index("Commands:") + 1 :]:
        if not line.strip():
            break
        match = re.match(r"^ {2}([a-z][a-z0-9-]*)(?:\s|$)", line)
        # NOTE: `help` prints the same page as `--help` and takes no options of
        # NOTE: its own, so documenting it would repeat every block on the page.
        if match is not None and match.group(1) != "help":
            names.append(match.group(1))
    return names


def command_paths(cli: Cli, path: tuple[str, ...] = ()) -> list[tuple[str, ...]]:
    """Every command the binary offers, parents before children.

    The list is discovered rather than written down, so a new subcommand is
    documented by the same change that adds it.
    """
    found = [path]
    for name in commands_in(cli.text([*path, "--help"])):
        found.extend(command_paths(cli, (*path, name)))
    return found


COMMANDS_INTRO = """\
# Commands

Each block below is the exact `--help` text of the binary this page was
generated from, so a flag documented here is a flag the tool has, and a flag
that is missing here does not exist.

`ocomment` with no command is `ocomment check`, and a command with no path is
the current directory. Findings, patches, listings, and every machine format go
to standard output; the run summary and every note go to standard error, so
`ocomment diff src > fix.patch` keeps the patch clean.

`check` exits `0` when nothing removable was found, `1` when removable comments
were reported or a diff was printed, and `2` for an invalid source,
configuration, plugin, or I/O failure.

The `Policy` and `Output` option groups are global. Every command that can act
on them accepts them, which is why the same two groups appear under most of the
blocks below. `ocomment man` renders the same material as a manual page."""


def commands_page(cli: Cli) -> str:
    """`docs/commands.md`: one `--help` block for every command, discovered."""
    paths = command_paths(cli)
    titles = [" ".join(("ocomment", *path)) for path in paths]
    lines = [BANNER, "", COMMANDS_INTRO, "", "## Contents", ""]
    lines.extend(f"- [`{title}`](#{anchor(title)})" for title in titles)
    for path, title in zip(paths, titles):
        help_text = cli.text([*path, "--help"])
        lines.extend(
            ["", f"## `{title}`", "", fence("console", f"$ {title} --help\n{help_text}")]
        )
    return "\n".join(lines) + "\n"


LANGUAGES_INTRO = """\
# Languages and dialects

`spec/languages.toml` is the canonical table. The `files:` pattern of the
published pre-commit hooks is generated from it, `tools/check_hooks.py` fails
when the two drift apart, and the table below is generated from the same file.
The binary embeds that same file, so `ocomment languages` prints these rows in
columns and `ocomment languages --format json` prints them as JSON.

A dialect changes the lexical rules rather than the file type: `--dialect
mysql` is still SQL, and only that dialect treats `/*!40101 ... */` as
something the server executes rather than as a comment.

A language is chosen from the file extension, and `--language` overrides that
for a run — which is what `ocomment strip` needs, because standard input has no
name. `--dialect` picks the dialect for the same run, and `[languages.<name>]
dialect = "..."` in `.ocomment.toml` picks one for everybody working in the
repository. An incompatible pair is an error rather than a silent fallback:

```console
$ ocomment strip --language rust --dialect mysql
ocomment: unsupported dialect `mysql` for rust; supported: standard
```
"""


NAMED_INTRO = """\
A file whose extension decides nothing is looked up by its whole name, and a
file with no name at all — a script on standard input — is read from its `#!`
line. A name is matched without regard to case, and a shebang matches when the
interpreter name appears anywhere on the line."""


def languages_page() -> str:
    """`docs/languages.md`: the shared language table, rendered."""
    with LANGUAGES.open("rb") as stream:
        table = tomllib.load(stream)
    entries = table["languages"]
    extensions = sorted({item for entry in entries for item in entry["extensions"]})
    dialects = sorted({item for entry in entries for item in entry["dialects"]})
    lines = [
        BANNER,
        "",
        LANGUAGES_INTRO,
        f"OComment has {count(len(entries), 'built-in language')} covering",
        f"{count(len(extensions), 'file extension')} and"
        f" {count(len(dialects), 'named dialect')}.",
        "",
        "| Language | Extensions | Dialects |",
        "| --- | --- | --- |",
    ]
    for entry in entries:
        dialect_of = entry.get("extension_dialects", {})
        suffixes = ", ".join(
            f"`.{item}` (`{dialect_of[item]}`)" if item in dialect_of else f"`.{item}`"
            for item in entry["extensions"]
        )
        forms = ", ".join(f"`{item}`" for item in entry["dialects"])
        lines.append(f"| `{cell(entry['name'])}` | {cell(suffixes)} | {cell(forms)} |")
    lines.extend(["", "## Detected without an extension", ""])
    lines.extend(NAMED_INTRO.splitlines())
    lines.extend(["", "| Language | File names | Shebangs |", "| --- | --- | --- |"])
    for entry in entries:
        names = ", ".join(f"`{item}`" for item in entry.get("reserved_names", ()))
        shebangs = ", ".join(f"`{item}`" for item in entry.get("shebangs", ()))
        if not names and not shebangs:
            continue
        lines.append(
            f"| `{cell(entry['name'])}` | {cell(names) or '—'} | {cell(shebangs) or '—'} |"
        )
    lines.extend(
        [
            "",
            "## Anything else",
            "",
            "HTML is scanned recursively: the contents of a `<script>` element are",
            "scanned as JavaScript and the contents of a `<style>` element as CSS,",
            "each with the comment forms of that language rather than of HTML.",
            "",
            "PHP is scanned in the code half of the file only. What sits between",
            "`<?php` (or `<?=`) and `?>` is scanned for PHP comments; the inline",
            "HTML around those tags is content, so an HTML `<!-- ... -->` comment",
            "in a PHP file is not reported and is never removed. Which mode a byte",
            "sits in is decided by everything above it, so only a line break in",
            "inline HTML is a point an editor may rescan a PHP file from: a file",
            "that is all PHP is rescanned from the top.",
            "",
            "Ruby is scanned with a lexer that keeps four states, because four",
            "of Ruby's tokens are spelled with a byte that is also an operator",
            "and only where the token stands decides which: `/` is a regular",
            "expression or a division, `%` a literal or a modulo, `?` a",
            "one-character string or a ternary, and `<<` a here document or an",
            "append. The fourth state is the one `alias` and `undef` leave Ruby",
            "in, where `%s` opens a symbol literal however it is spaced while",
            "`%w`, `%q` and `/` after the same keyword stay operators.",
            "Ruby's own parser answers those from a lexer state that a",
            "symbol table feeds -- it knows whether `a` is a local variable or a",
            "method -- and a scanner has no symbol table, so a bare word is",
            "always read as a method that may take a command argument. `a /b/ c`",
            "is therefore a pattern here where Ruby, knowing `a` to be a",
            "variable, reads two divisions. The reading that differs is the one",
            "that keeps more bytes inside a literal, so a comment is never",
            "invented out of a division; it is a comment left unfound, not a",
            "byte removed.",
            "",
            "Three smaller readings go the same way. A `/` inside a character",
            "class stays inside the pattern, where Ruby's own lexer ends the",
            "literal at it, so `/[/]/` is one regular expression. `$#`, which",
            "Ruby refuses outright as a global variable name, is read as a `$`",
            "and then the comment that `#` opens everywhere else. And a here",
            "document terminator may be spelled with digits, because Ruby",
            "builds an unquoted one out of name bytes and a digit is one of",
            "those from the first byte on: `puts <<2` opens a here document",
            "that runs to a line reading `2`, and every line between the two",
            "is body rather than code. Where the same `<<` follows an operand",
            "-- `a[0] <<2`, `p 1 <<2` -- it is the shift operator it looks",
            "like, and the rest of that line is code.",
            "",
            "Zig is the one built-in language with no block comment. `/*` is the",
            "division operator followed by multiplication, so a `/* ... */`",
            "written in a Zig file is code: it is not reported and it is never",
            "removed. `///` and `//!` are documentation comments and a fourth",
            "slash takes the marker back, so `////` is an ordinary one. A",
            "multiline string literal is read one line at a time: a `\\\\`",
            "wherever a token may begin runs to the end of that line as string",
            "content, and the line under it starts in code again. `zig fmt: off`",
            "and `zig fmt: on` are kept, and they are matched as the whole",
            "phrase the formatter compares rather than as a prefix of it.",
            "",
            "R has one comment token and `#` opens it, so what the scanner has",
            "to know is the four literals that carry a `#` as content. Two are",
            "quoted strings and both may run over a line break; the third is a",
            "backquoted name, which is lexed the same way; and the fourth is",
            "the `%...%` operator, whose name is every byte up to the next `%`",
            "on the same line -- `x %a # b% y` is one operator, and a `%` with",
            "no second `%` before the line break is an error rather than a",
            "comment opener. A raw string is `r` or `R`, a quote, any run of",
            "dashes and one of `(`, `[` or `{`, and it closes only on the",
            "matching bracket with the same run of dashes and the same quote.",
            "The `r` opens one only where it begins a token, so the quote in",
            "`xr\"(a)\"` opens an ordinary string instead. `#'` is roxygen2's",
            "documentation marker and is a `doc-line`; R's own parser calls",
            "every one of these a comment and draws no distinction.",
            "",
            "Dart is the one built-in C-family language whose block comment",
            "nests, so `/* /* */ */` is one comment and commenting out a region",
            "that already holds one works. Its documentation markers are `///`",
            "and `/**`, decided at the single byte behind the opener: a fourth",
            "slash leaves `////` documentation, where Lua's `----` and Zig's",
            "`////` take the marker back, and `//!` and `/*!` document nothing.",
            "A string is written six ways -- either quote, single-line or",
            "triple-quoted, raw or not -- and only the `r` of a raw one takes",
            "away the `\\` escape and `${ ... }` interpolation. That",
            "interpolation is code, so a comment written inside one is a",
            "comment, and a `//` there ends at the line break while the string",
            "around it carries on below. `#` opens a symbol literal and is a",
            "comment only as the `#!` script tag at the very first byte of a",
            "file. `// @dart = 2.12` is kept because the language version it",
            "names changes what the rest of the file means, and",
            "`// dart format off` and `// dart format on` are matched as the",
            "whole phrase `dart_style` compares rather than as a prefix.",
            "",
            "Swift's block comment nests as Dart's does, `///` and `/**`",
            "document -- `////` still does and the empty `/**/` does not, since",
            "its second `*` is the first byte of its own terminator -- and `//!`",
            "and `/*!` document nothing. A string is written four ways: single",
            "line or `\"\"\"`, each of them raw or not, where raw is a run of `#`",
            "in front of the quote. Those hashes do not take the escape and the",
            "interpolation away, they *rename* them: with one hash the escape",
            "is `\\#` and `\\#(` opens the interpolation, the closing delimiter",
            "needs the same run behind the quote, and a bare `\\(` is content.",
            "The interpolation is code, so a comment written inside one is a",
            "comment.",
            "",
            "The regular expression literal is the one thing in Swift that can",
            "carry a `//` with no quote in front of it, and only JavaScript's",
            "scanner faces the construct at all besides this one. `#/ ... /#`",
            "is the extended form, which may hold an unescaped `/` and, when",
            "its opener ends the line, may span lines. The bare `/ ... /` ends at",
            "the first unescaped `/`, never crosses a line, and may not begin",
            "with a space or a tab (The Swift Programming Language, Lexical",
            "Structure) -- and its last two bytes may still spell `//`, because",
            "`/a\\//` is a literal whose content is `a\\/`. One rule cannot be",
            "had from the bytes alone: whether a `/` in an ambiguous position",
            "is a literal at all is settled in Swift by the *parser*, and this",
            "is a lexer. It reads a `/` as a literal exactly where a prefix",
            "operator may stand and where the content closes on the same line;",
            "every case that decides differently from the compiler is a file",
            "`swiftc` rejects, where the compiler is lexing a literal it has",
            "already diagnosed and this reads the comment inside it instead --",
            "so a `fix` on a file that does not compile can take the two bytes",
            "of a comment opener a repaired file would have kept. The corpus",
            "case `swift-bare-regex-limitation` records one.",
            "`'` is no delimiter of the language, but the compiler",
            "lexes `'...'` anyway so that it can offer a fix-it, and this",
            "follows it for the same reason.",
            "",
            "C# is the one built-in language whose *lines* are lexed two ways.",
            "A line whose first non-blank byte is `#` is a pre-processing",
            "directive, and ECMA-334 6.5.1 ends one with",
            "`PP_Whitespace? SINGLE_LINE_COMMENT? New_Line`: a `//` is the only",
            "comment it can carry, a `/*` on it opens nothing, and a `\"` opens",
            "a string that takes no `\\` escape and ends at the line -- which is",
            "what keeps the `//` inside `#line 1 \"a//b.cs\"` out of reach. Four",
            "directives take the rest of their line as a message instead:",
            "`#error` and `#warning` carry the text a diagnostic quotes, and",
            "`#region` and `#endregion` the label an editor folds under, so",
            "`#region // x` carries a comment and `#region x // y` does not. A",
            "conditional section is scanned as ordinary code rather than",
            "skipped, for the reason `#if 0` is in C and C++: which symbols a",
            "build defines is not in the file, and code is what an `#if DEBUG`",
            "body is in every build that defines the symbol. The price is a",
            "section written to be skipped rather than compiled -- prose, or",
            "another language -- whose bytes are not C#: an apostrophe in one",
            "opens a character literal its line does not close, so the file is",
            "called invalid and no edit is offered for it, where Roslyn reports",
            "the whole section as one blob of disabled text and finds nothing",
            "in it. Refusing to edit is the safe half of being wrong, and two",
            "files of the 70,630 measured are affected -- both of them a block",
            "of prose under an `#if false`, and the only two this scanner calls",
            "invalid that Roslyn does not. The corpus case",
            "`csharp-conditional-section-limitation` records one.",
            "",
            "A string is written eight ways -- plain, verbatim, raw, and each of",
            "those interpolated -- and the three rules differ in what closes",
            "them. A plain one takes the `\\` escape, which carries the",
            "character behind it in whatever it is, a line terminator included;",
            "a verbatim `@\"...\"` spells its quote `\"\"`, takes no escape, and",
            "carries line breaks; and a raw one is opaque until a run of at",
            "least as many quotes as its opener carried comes back, carrying",
            "line breaks only when its opener ends a line. Interpolation is a",
            "switch on top of all three: a run of `n` `$` in front of the quote",
            "makes a run of `n` braces the thing that opens a hole, so `{` is",
            "content in a `$$\"\"\"` literal and `{{` is code. A hole is code, so",
            "a comment written in one is a comment and may carry a line break",
            "the text around it could not -- but the format clause behind the",
            "first `:` of a hole is text again, which is why the `//` in",
            "`$\"{x:D4 // n}\"` is not a comment and why `$\"{global::X}\"` needs",
            "the parentheses the compiler asks for.",
            "",
            "C# also counts five line terminators where every other C-family",
            "scanner here counts two: ECMA-334 6.3.1 adds U+0085, U+2028 and",
            "U+2029 to the carriage return and line feed, and Roslyn ends a",
            "`//` comment at all five. A scanner that read on past one would",
            "swallow the code behind it on the same physical line, and a",
            "removal would take that code with it.",
            "",
            "Scala's block comment nests as Dart's does, and its documentation",
            "comment is the one the Scala 3 compiler's comment reader answers to:",
            "a comment is documentation exactly when its text starts with `/**`",
            "(`Comment.isDocComment`), so `/**/` and `/***/` are documentation",
            "comments and `///` -- which scaladoc does not read -- is an ordinary",
            "line comment.",
            "",
            "A Scala string is interpolated exactly when an identifier stands",
            "directly before its quote: the compiler's lexer turns that",
            "identifier into `INTERPOLATIONID`, so `s\"...\"`, `raw\"...\"` and a",
            "custom interpolator such as `xml\"...\"` interpolate, while a",
            "keyword -- its own token -- and a number leave the quote to a plain",
            "string whose `$` is content. Inside an interpolated string `$$` and",
            "`$\"` write a literal `$` and `\"`, `${ ... }` opens an expression",
            "that is code -- a comment written there is a comment -- and `$`",
            "followed by an identifier starts another one. A triple-quoted",
            "string closes on the first three quotes of a run and makes any",
            "further quotes of the run part of its value, so `\"\"\"a\"\"\"\"` is",
            "the string `a\"`; a backquoted identifier may hold `//` without it",
            "being a comment.",
            "",
            "The XML literal is the one Scala construct whose text is not code:",
            "the compiler's *lexer* emits an `XMLSTART` token and the parser",
            "re-reads the literal with an XML scanner, so this scanner reads it",
            "the way the parser does. Element text, CDATA and processing",
            "instructions are opaque, `{ ... }` in text or an attribute is code,",
            "`<!-- ... -->` is an XML comment, and the literal ends at the close",
            "tag matching its root or at a self-closing `/>`. A literal begins",
            "exactly where the lexer says one does: a `<` preceded by space,",
            "tab, line feed, `{`, `(` or `>` and followed by an XML name start,",
            "`!` or `?`.",
            "",
            "YAML is scanned lexically, and `valid` is a lexical answer: the",
            "shapes a YAML *parser* rejects are not all shapes a lexer can see.",
            "A comment line inside a multi-line plain scalar makes the file a",
            "parse error while it is there, and taking it away leaves a scalar",
            "that parses and folds the two halves into one value; that comment",
            "is reported and removed like any other.",
            "",
            "The block scalar is the other way round, and it is the one place",
            "in any language where the *hole* a removal leaves carries meaning.",
            "A block scalar decides where its body ends from the lines below it",
            "(YAML 1.2.2, 8.1.1), so a whole-line comment under a body is what",
            "terminates it -- and whatever a removal writes on that line is read",
            "back as part of the value. A line of spaces as wide as the comment,",
            "which `columns` writes, is indented at least as deep as the body",
            "whenever the comment was wide enough. An empty line, which `lines`",
            "writes, is content under `|+` and `>+`, which keep every empty line",
            "trailing a body (8.1.1.2).",
            "",
            "So the rule is one rule, and it holds whatever the block scalar",
            "chomps: **a whole-line comment sitting in the run of blank and",
            "comment lines under a block scalar body is removed by taking its",
            "whole line, terminator and all, under every layout.** Those lines",
            "are the one place `lines` does not keep a line's number and",
            "`columns` does not keep a column's -- both give that up rather than",
            "give up the value. Under `|+` and `>+` the removal also takes the",
            "blank lines the comment was sheltering, which become content the",
            "moment it is gone; the blank lines *above* the first comment were",
            "content already and are left exactly where they were.",
            "",
            "There is one comment that rule cannot reach, and it is kept instead.",
            "The line a body ends at is a comment shallower than the body's own",
            "content; take it away and the lines under it are read against the body",
            "again. When one of those is a comment the run *keeps*, and it is",
            "indented to the content depth, the body swallows it and the value",
            "grows a line. No removal preserves the value there, so the comment",
            "that ends the body is kept, with the reason `structural in a YAML",
            "block scalar trail` -- the one keep `--policy all` does not overrule.",
            "",
            "The depth this is measured at is the body's *content* indentation:",
            "the explicit indentation indicator when the header spells one out, and",
            "otherwise the indentation of the body's first non-empty line (YAML",
            "1.2.2, 8.1.1.1). A surviving comment shallower than that is outside",
            "the scalar before and after the removal, so nothing above it is kept.",
            "",
            "`tools/yaml_roundtrip.py` is what holds this to its word: it strips",
            "thousands of generated YAML documents under every layout and every",
            "policy and asserts that PyYAML reads the same value out of each one",
            "before and after.",
            "",
            "A delimiter-based syntax that is not in the table above can be described",
            "declaratively as a profile in `.ocomment.toml`, which needs no code; see",
            "[Configuration](configuration.md). A syntax whose comments cannot be",
            "described by delimiters alone needs a scanner plugin instead; see",
            "[Plugins](plugins.md).",
        ]
    )
    return "\n".join(lines) + "\n"


POLICIES = ("safe", "legal", "all")
LAYOUTS = ("lines", "columns", "compact")

POLICY_SAMPLE = """\
// SPDX-License-Identifier: MIT OR Apache-2.0

// rustfmt::skip
/// Adds two numbers.
pub fn add(a: u32, b: u32) -> u32 {
    let total = a + /* widen */ b; // TODO: check for overflow
    /* Everything from here down is one block comment
       that runs across three lines, so each layout has
       something to show. */
    total
}
"""

POLICIES_INTRO = """\
# Policies and layouts

Two settings decide what a run does, and they are independent of each other. A
**policy** decides which comments may be removed at all. A **layout** decides
what is left behind where a removed comment used to be. Both are available as
`--policy` and `--layout` on the command line, as `mode` and `layout` under
`[policy]` in `.ocomment.toml`, and as `policy` and `layout` on an
`[[overrides]]` entry that matches a path.

Every before-and-after pair on this page was produced by running the sample
below through `ocomment strip`, so the outputs are the real bytes, trailing
spaces included."""


def policies_page(cli: Cli, workspace: pathlib.Path) -> str:
    """`docs/policies.md`: what each policy and layout does to a fixed sample.

    Every run is made from `workspace`, which holds no `.ocomment.toml`, so the
    outputs are what the named policy and layout do on their own rather than
    what this repository's own configuration would have made of the sample.
    """
    source = POLICY_SAMPLE.encode("utf-8")
    lines = [
        BANNER,
        "",
        POLICIES_INTRO,
        "",
        "## The sample",
        "",
        fence("rust", POLICY_SAMPLE),
        "",
        "It carries a licence header, a tool directive, a documentation comment,",
        "an inline block comment between two tokens, a trailing comment, and a",
        "block comment that spans several lines.",
        "",
        "## What each policy removes",
        "",
        "Each of these is `ocomment strip --language rust --policy <mode>` reading",
        "the sample on standard input.",
    ]
    for policy in POLICIES:
        output = cli.text(
            ["strip", "--language", "rust", "--policy", policy],
            source=source,
            cwd=workspace,
        )
        lines.extend(
            [
                "",
                f"### `{policy}`",
                "",
                fence("text", output),
            ]
        )
    lines.extend(
        [
            "",
            "`safe` and `legal` differ over the licence header alone, and `all`",
            "is the only one that takes the `// rustfmt::skip` directive out.",
            "`all` still refuses to touch a shebang or an encoding preamble until",
            "`--force-protected` is given as well; see",
            "[Why was this comment kept?](why-kept.md).",
            "",
            "## What each layout leaves behind",
            "",
            "Each of these is `ocomment strip --language rust --layout <layout>`",
            "reading the same sample, under the default `safe` policy.",
        ]
    )
    outputs = {}
    for layout in LAYOUTS:
        outputs[layout] = cli.text(
            ["strip", "--language", "rust", "--layout", layout],
            source=source,
            cwd=workspace,
        )
        lines.extend(["", f"### `{layout}`", "", fence("text", outputs[layout])])
    # INVARIANT: the paragraph below tells the reader that `lines` and `columns`
    # INVARIANT: keep the line count of the file, which is the property that keeps
    # INVARIANT: a line number in a stack trace pointing at the same statement, and
    # INVARIANT: that `compact` is the one layout that gives it up. A layout that
    # INVARIANT: stopped doing either has to fail here rather than ship a page that
    # INVARIANT: says it still does.
    expected_lines = POLICY_SAMPLE.count(chr(10))
    for layout, output in outputs.items():
        counted = output.count(chr(10))
        if layout == "compact":
            if counted >= expected_lines:
                raise SystemExit(
                    f"layout `compact` left all {expected_lines} lines standing;"
                    " docs/policies.md claims it drops the lines a removed comment"
                    " had to itself"
                )
        elif counted != expected_lines:
            raise SystemExit(
                f"layout `{layout}` turned {expected_lines} lines into"
                f" {counted}; docs/policies.md claims the line count is preserved"
            )
    same = [
        f"`{first}` and `{second}`"
        for first, second in itertools.combinations(LAYOUTS, 2)
        if outputs[first] == outputs[second]
    ]
    lines.append("")
    if same:
        lines.extend(
            [
                f"On this sample {' and '.join(same)} leave the same bytes.",
                "",
            ]
        )
    lines.extend(
        [
            "`lines` and `columns` keep the line count of the file: a comment that",
            "spanned three lines is replaced by something that still spans three",
            "lines, so a line number in a stack trace or a `git blame` still points",
            "at the same statement. `columns` additionally keeps every following",
            "column in place by padding with spaces, which is what a table of",
            "aligned initialisers or a column-sensitive language wants, at the cost",
            "of trailing whitespace that a formatter may then remove.",
            "",
            "`compact` is the layout that gives line numbers up. A line that held",
            "nothing but a removed comment goes away with it, terminator included,",
            "and the whitespace a removal would leave at the end of a line is",
            "trimmed. Code keeps its own lines: a comment sharing a line with code",
            "leaves that line, its terminator and its CRLF or LF style as they",
            "were. A surviving line keeps the ending it had in the source - the",
            "same LF or CRLF, from inside the comment if that is where it was - or",
            "no ending at all if the file stopped there without one.",
            "",
            "## Where they are set",
            "",
            "```toml",
            "version = 1",
            "",
            "[policy]",
            'mode = "legal"',
            'layout = "lines"',
            "",
            "[[overrides]]",
            'paths = ["generated/**"]',
            'policy = "all"',
            'layout = "compact"',
            "```",
            "",
            "The flag wins over the file, and an `[[overrides]]` entry whose globs",
            "match the path wins over `[policy]`. `ocomment config explain` prints",
            "the resolved values and where each came from, and `ocomment --explain`",
            "names the rule and the setting behind any one comment.",
        ]
    )
    return "\n".join(lines) + "\n"


WHY_CONFIG = r"""version = 1

[policy]
mode = "safe"
keep_regex = ['^//\s*NOTE\b']

[[overrides]]
paths = ["gen/**"]
policy = "all"
keep_regex = ["(?i)generated"]
"""

WHY_FIXTURE = {
    "gen/api.rs": "/* generated by build.rs */\npub const VERSION: u32 = 1; // bump me\n",
    "src/app.js": "// eslint-disable-next-line no-console\nconsole.log(1); // TODO: drop\n",
    "src/lib.rs": "// NOTE: the retry budget is what the server documents.\nfn main() {}\n",
}

WHY_INTRO = """\
# Why was this comment kept?

A run that reports fewer comments than you expected has not lost them: it
decided to keep them, and it can say which rule decided. `--explain` lists every
comment a human `check` or `scan` met, the kept ones included, and puts the rule
and the setting behind that rule on the line under each one.

`--explain` annotates a report of comments, so it belongs to the two commands
that write one. Asking for it with `--format json`, or any other machine format,
or with a command that writes no report of comments, is a usage error rather
than a flag that quietly does nothing."""

WHY_WALKTHROUGH = """\
## Ask the binary

This project has a generated directory, a JavaScript file with a lint
directive, and a house rule that a `NOTE:` comment is deliberate:

```toml
%(config)s```

```text
%(tree)s```

`--explain` names the rule and the setting behind every comment it meets —
%(comments)s in this project:

```console
$ ocomment check --explain
%(transcript)s```

Read the second line of each pair as the answer. A `keep_regex` match kept the
first comment even though `[[overrides]]` puts the whole `gen/**` tree under the
`all` policy; a marker the scanner recognises kept the lint directive with no
configuration at all; and the setting in brackets is named where it was written,
so `[policy] in .ocomment.toml` and `[[overrides]] #0` point at the two places
that decided this run. A comment no setting decided is left with the flag that
would overrule the built-in rule instead."""


def scan_comments(
    cli: Cli, language: str, dialect: str | None, source: bytes, cwd: pathlib.Path
) -> list[dict]:
    """Every comment the binary reports for one sample, in source order."""
    arguments = ["scan", "--format", "json", "--language", language]
    if dialect is not None:
        arguments += ["--dialect", dialect]
    document = json.loads(cli.text(arguments + ["-"], source=source, cwd=cwd))
    return document["files"][0]["report"]["comments"]


def policy_matrix() -> list[str]:
    """The policy-by-kind table, straight out of `spec/directives.toml`."""
    with DIRECTIVES.open("rb") as stream:
        table = tomllib.load(stream)
    policies = {name: table["policy"][name] for name in POLICIES}
    kinds: list[str] = []
    for name in POLICIES:
        for key in ("remove", "keep", "keep_without_force_protected"):
            for kind in policies[name].get(key, []):
                if kind not in kinds:
                    kinds.append(kind)
    header = " | ".join(f"`{name}`" for name in POLICIES)
    lines = [
        f"| Comment kind | {header} |",
        "| --- | " + " | ".join(["---"] * len(POLICIES)) + " |",
    ]
    for kind in kinds:
        cells = []
        for name in POLICIES:
            policy = policies[name]
            if kind in policy.get("remove", []):
                cells.append("removed")
            elif kind in policy.get("keep", []):
                cells.append("kept")
            elif kind in policy.get("keep_without_force_protected", []):
                cells.append("kept unless `--force-protected`")
            else:
                # INVARIANT: a kind no policy mentions would render as an empty
                # INVARIANT: cell that reads like "nothing happens to it", which
                # INVARIANT: is a claim this table cannot make.
                raise SystemExit(
                    f"`{kind}` is in no list of policy `{name}` in"
                    f" {DIRECTIVES.relative_to(ROOT)}"
                )
        lines.append(f"| `{cell(kind)}` | " + " | ".join(cells) + " |")
    return lines


def protected_table(cli: Cli, cwd: pathlib.Path) -> list[str]:
    """One row per marker `spec/directives.toml` protects, scanned for real."""
    with DIRECTIVES.open("rb") as stream:
        names = tomllib.load(stream)["protected"]
    lines = [
        "| Marker | Language | Written as | Kind | Kept because |",
        "| --- | --- | --- | --- | --- |",
    ]
    for name in names:
        if name not in PROTECTED_SAMPLES:
            raise SystemExit(
                f"`{name}` is protected by {DIRECTIVES.relative_to(ROOT)} and has no"
                f" sample in {pathlib.Path(__file__).name}"
            )
        language, dialect, source = PROTECTED_SAMPLES[name]
        comments = scan_comments(cli, language, dialect, source, cwd)
        if len(comments) != 1:
            raise SystemExit(
                f"the sample for `{name}` holds {count(len(comments), 'comment')},"
                " so the row would describe the wrong one"
            )
        comment = comments[0]
        span = comment["span"]
        text = source[span["start"] : span["end"]].decode("utf-8")
        disposition = comment["disposition"]
        if disposition.get("action") != "keep":
            raise SystemExit(
                f"`{name}` is listed as protected but the binary reports"
                f" {disposition} for {text!r}"
            )
        lines.append(
            f"| `{cell(name)}` | `{cell(language if dialect is None else dialect)}` |"
            f" `{cell(text)}` | `{cell(comment['kind'])}` |"
            f" {cell(disposition['reason'])} |"
        )
    return lines


def why_kept_page(cli: Cli, workspace: pathlib.Path) -> str:
    """`docs/why-kept.md`: the rules that keep a comment, and how to see them."""
    fixture = workspace / "why-kept"
    for name, body in WHY_FIXTURE.items():
        path = fixture / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(body, encoding="utf-8", newline="\n")
    (fixture / ".ocomment.toml").write_text(WHY_CONFIG, encoding="utf-8", newline="\n")
    completed = cli.run(["check", "--explain"], cwd=fixture, expected=(1,))
    transcript = completed.stdout.decode("utf-8") + completed.stderr.decode("utf-8")
    tree = "".join(f"{name}\n" for name in [".ocomment.toml", *WHY_FIXTURE])
    # NOTE: a reported comment starts at the left margin and the rule under it is
    # NOTE: indented, so the unindented lines are the comments the run met.
    reported = sum(
        1
        for line in completed.stdout.decode("utf-8").splitlines()
        if line and not line.startswith(" ")
    )

    lines = [
        BANNER,
        "",
        WHY_INTRO,
        "",
        WHY_WALKTHROUGH
        % {
            "config": WHY_CONFIG,
            "tree": tree,
            "transcript": transcript,
            "comments": count(reported, "comment"),
        },
        "",
        "## What each policy removes",
        "",
        "`spec/directives.toml` is the shared table both implementations are",
        "checked against, and this is that table. `--policy` and `[policy] mode`",
        "choose a column, and the settings in the next sections move a single",
        "comment out of the column its kind lands in.",
        "",
    ]
    lines.extend(policy_matrix())
    lines.extend(
        [
            "",
            "## Markers that survive a removal",
            "",
            "Some comments are not commentary at all: a build tag, a lint control,",
            "or an optimiser hint changes what a compiler, a linter, or a database",
            "does with the file. Each row below is scanned by the binary that built",
            "this page, so the table cannot claim a protection that is not there.",
            "",
        ]
    )
    lines.extend(protected_table(cli, workspace))
    lines.extend(
        [
            "",
            "`--remove-kind directive` or `--policy all` removes a directive anyway.",
            "A shebang and an encoding preamble need `--force-protected` on top of",
            "`--policy all`, because removing one changes how the file is executed",
            "or decoded rather than how it reads.",
            "",
            "## The one keep no setting reaches",
            "",
            "Every rule above is about what a comment *says*. One is about where it",
            "sits, and it is the only keep no flag overrules:",
            "",
            "```yaml",
            "k: |",
            "  a",
            "# ends the block",
            "  # yamllint disable",
            "z: 1",
            "```",
            "",
            "A YAML block scalar decides where its body ends from the lines below",
            "it, so `# ends the block` is not commentary: it is what terminates the",
            "body, and the directive under it is indented deep enough to be content",
            "of that body. Remove the terminating line -- and a removal there takes",
            "the whole line, which is the least it can take -- and the directive",
            "rejoins the scalar, so `k` changes from `a` to two lines. No removal",
            "preserves the value, so the comment stays, and `--explain` writes the",
            "reason under it:",
            "",
            "```text",
            "k.yaml:3:1: kept line comment: # ends the block",
            "    kept: it separates a `yaml` block scalar from the kept comment"
            " below it; the comment under it has to go first",
            "```",
            "",
            "`--policy all` is not a way out: it removes the directive as well, and",
            "with nothing left standing under the body both comments go. What holds",
            "the first one in place is whatever comment survives *under* it, so that",
            "is the line to take first. A surviving comment shallower than the",
            "body's own content ends the scalar on its own and keeps nothing above",
            "it -- see [Languages](languages.md) for the depth this is measured at.",
            "",
            "## Keeping more",
            "",
            "```toml",
            "version = 1",
            "",
            "[policy]",
            "keep_kind = [\"doc-line\", \"doc-block\"]",
            r"keep_regex = ['^(//|\(\*|/\*|#)\s*(NOTE|SAFETY|INVARIANT|PERF)\b']",
            "",
            "[[overrides]]",
            'paths = ["vendor/**"]',
            'policy = "legal"',
            "```",
            "",
            "`keep_kind` names whole kinds from the first column of the table above,",
            "so `keep_kind = [\"doc-line\", \"doc-block\"]` takes documentation out of",
            "reach of every policy. `keep_regex` matches the comment token itself,",
            "delimiters included, which is what lets `^//` anchor a rule to the start",
            "of the comment; this repository uses exactly that to require a tag on",
            "every explanatory comment it keeps. Both are lists, and `--explain`",
            "reports the index it matched, so `keep_regex #0` is the first entry.",
            "",
            "## Keeping less",
            "",
            "`--remove-kind` is the mirror of `keep_kind` and removes a kind the",
            "policy would have kept. `--policy all` removes every kind at once.",
            "`--force-protected` is needed on top of it for a shebang or an encoding",
            "preamble. `--force-invalid` applies the edits that are still provably",
            "safe in a file that failed to scan, and is the only one of these that",
            "is about a broken file rather than about a policy.",
            "",
            "## When the answer is still surprising",
            "",
            "`ocomment config explain` prints the resolved configuration and where",
            "each value came from, `ocomment doctor` reports the environment around",
            "it, and `ocomment scan --format json` gives the byte span and kind of",
            "every comment for a tool to read.",
        ]
    )
    return "\n".join(lines) + "\n"


def render(cli: Cli, workspace: pathlib.Path) -> dict[pathlib.Path, str]:
    """Every generated page, keyed by the file it belongs in."""
    return {
        DOCS / "commands.md": commands_page(cli),
        DOCS / "languages.md": languages_page(),
        DOCS / "policies.md": policies_page(cli, workspace),
        DOCS / "why-kept.md": why_kept_page(cli, workspace),
    }


def difference(path: pathlib.Path, expected: str, actual: bytes | None) -> str:
    """What to print about one page that is missing or out of date."""
    relative = path.relative_to(ROOT)
    if actual is None:
        return f"{relative} does not exist"
    diff = difflib.unified_diff(
        actual.decode("utf-8", "replace").splitlines(keepends=True),
        expected.splitlines(keepends=True),
        fromfile=f"{relative} (checked in)",
        tofile=f"{relative} (regenerated)",
        n=1,
    )
    body = "".join(itertools.islice(diff, 40))
    return f"{relative} is out of date\n{body.rstrip(chr(10))}"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--binary",
        type=pathlib.Path,
        help="the ocomment to generate from (default: the debug or release build)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of writing when a page is missing or out of date",
    )
    args = parser.parse_args()

    binary = args.binary
    if binary is None:
        binary = next((path for path in DEFAULT_BINARIES if path.is_file()), None)
        if binary is None:
            parser.error(
                "no ocomment binary was found; build one with"
                " `cargo build --manifest-path rust/Cargo.toml --locked -p ocomment`"
                " or name one with --binary"
            )
    binary = binary.resolve()
    if not binary.is_file():
        parser.error(f"CLI binary does not exist: {binary}")

    failures: list[str] = []
    with tempfile.TemporaryDirectory() as directory:
        workspace = pathlib.Path(directory)
        (workspace / "config").mkdir()
        cli = Cli(binary, workspace)

        rendered = cli.run(["man"]).stdout
        if not MAN_PAGE.is_file():
            failures.append(f"{MAN_PAGE.relative_to(ROOT)} does not exist")
        elif MAN_PAGE.read_bytes() != rendered:
            failures.append(
                f"{MAN_PAGE.relative_to(ROOT)} is not what `ocomment man` renders;"
                " regenerate it with `python3 tools/release_extras.py"
                " --binary rust/target/debug/ocomment` and copy"
                " release-extras/ocomment.1 to docs/"
            )

        pages = render(cli, workspace)
        written = 0
        stale = 0
        for path, expected in pages.items():
            wanted = expected.encode("utf-8")
            actual = path.read_bytes() if path.is_file() else None
            if actual == wanted:
                continue
            if args.check:
                failures.append(difference(path, expected, actual))
                stale += 1
            else:
                path.write_bytes(wanted)
                written += 1

    if failures:
        print("\n".join(failures))
        # NOTE: the manual page is checked here but written by another tool, so
        # NOTE: naming this one would send a reader to a command that cannot fix
        # NOTE: what they were just told about.
        if stale:
            print(f"Regenerate with: {REGENERATE}")
        return 1
    if args.check:
        print(
            f"{count(len(pages), 'generated documentation page')}"
            " and the manual page match the binary and spec/"
        )
    else:
        print(
            f"{count(written, 'generated documentation page')} rewritten;"
            f" {count(len(pages) - written, 'page')} already current"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
